---
services:
  tubearchivist:
    image: bbilly1/tubearchivist
    container_name: tubearchivist
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=192.168.42.10 100.88.78.27
      - TA_USERNAME=admin
      - TA_PASSWORD=${TA_PASSWORD}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_DISABLE_VERIFY_SSL=true
      - TZ=Europe/Berlin
    volumes:
      - /opt/docker/volumes/tubearchivist:/cache
      - /mnt/media/youtube:/youtube
    ports: 
      - 8000:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    expose:
      - "6379"
    volumes:
      - /opt/docker/volumes/archivist-redis:/data
    restart: unless-stopped
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/docker/volumes/archivist-es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    restart: unless-stopped
