---
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: "unless-stopped"
    volumes:
      - /opt/docker/volumes/thelounge:/var/opt/thelounge
